### ISSUE TITLE
Server failed to start on recent Ubuntu due to too low max_connections

### ISSUE THREAD

**Issue by dev-zero** [jamesnunn/pgtest#14]
It seems that the most recent version of PostgreSQL in the `ubuntu:rolling` image increased the required amount of connections even more. In that image startup fails with the following message:

```
postgres: superuser_reserved_connections (3) plus max_wal_senders (10) must be less than max_connections (11)
```

My guess is that the number of `superuser_reserved_connections` got increased to 3, which makes to total amount of required connections now `13`.

I'd recommend to increase it to 15.

@ltalirz fyi

**Comment by ltalirz** [comment]
@jamesnunn By the way, is there a good reason for specifying a default number for the max allowed connections in pgtest?
What about simply using the default of the respective postgres version?

**Comment by dev-zero** [comment]
Btw, it would help a lot for debugging if in case of an error the `self._log_file` is read and appended to the output.

**Comment by ltalirz** [comment]
> Btw, it would help a lot for debugging if in case of an error the self._log_file is read and appended to the output.

@dev-zero I'm sure @jamesnunn would happily accept a PR for this

**Comment by ltalirz** [comment]
@jamesnunn I'm going to prepare a PR for this - I'll be removing the  max allowed connections default unless otherwise instructed
