### ISSUE TITLE
Do not assume that locate command is available

### ISSUE THREAD

**Issue by danielhollas** [jamesnunn/pgtest#25]
When trying to find the `pg_ctl` binary, this package uses the `locate` command as a fallback when the command is not found in `$PATH`.

https://github.com/jamesnunn/pgtest/blob/417f0d89e66a9395db694a96122e0d5ac0097d59/pgtest/pgtest.py#L117

However, `locate` command itself might not be available, for example in Docker containers. In this case, the package crashes with rather unhelpful stacktrace.

**Comment by ltalirz** [comment]
That's a great point. A pull request that adds a clean try/except for the availability of locate would be much appreciated
