### ISSUE TITLE
pypi release does not contain max_connections

### ISSUE THREAD

**Issue by DropD** [jamesnunn/pgtest#6]
It would be nice to have this in a pypi release so it can be used as a requirement in other pypi packages.

**Comment by jamesnunn** [comment]
There ya go https://pypi.python.org/pypi/pgtest/1.1.0

It appears the Travis build is failing but I ran the same tests just now locally and it's all fine.

**Comment by DropD** [comment]
i had the same problem with the travis tests and they ran after changing to 
```
dist: trusty
addons:
  postgresql: "9.5"
```
