### ISSUE TITLE
pgtest fails on ubuntu 18.04

### ISSUE THREAD

**Issue by yakutovicha** [jamesnunn/pgtest#8]
Pgtest fails on ubuntu 18.04, as it cannot find the pg_ctl:

```
In [1]: from pgtest.pgtest import PGTest

In [2]: import psycopg2

In [3]: pg = PGTest()
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-3-037313004511> in <module>()
----> 1 pg = PGTest()

/home/epfl/work/venv-lsmo/local/lib/python2.7/site-packages/pgtest/pgtest.py in __init__(self, username, port, log_file, no_cleanup, copy_cluster, base_dir, pg_ctl, max_connections)
    308 
    309         self._create_dirs()
--> 310         self._init_base_dir()
    311         self._set_dir_permissions()
    312         self._start_server()

/home/epfl/work/venv-lsmo/local/lib/python2.7/site-packages/pgtest/pgtest.py in _init_base_dir(self)
    461                 _, err = proc.communicate()
    462                 if err:
--> 463                     raise IOError(err)
    464             assert is_valid_cluster_dir(self._cluster), (
    465                 'Failed to create cluster: {path}').format(path=self._cluster)

IOError: /bin/sh: 1: None: not found
```

**Comment by yakutovicha** [comment]
Maybe one should call "pg_ctlcluster" instead of "pg_ctl"? 
According to [this discussion,](https://dba.stackexchange.com/a/156722) there is no reason to ever call pg_ctl directly.

What do you guys think?

**Comment by jamesnunn** [comment]
It could be called on the start/stop methods but `pg_ctlcluster` doesn't seem to be able to run `initdb`. I don't have time at the moment to look into it but if you can find a way to do this, send a pull request and I'll review

**Comment by DropD** [comment]
It seems the debian way would be to use the `pg_createcluster` script. Seems it can create and start a cluster in one go:

```
$ pg_createcluster
Usage: /usr/bin/pg_createcluster [options] <version> <cluster name> [-- <initdb options>]

Options:
  -u <uid>      cluster owner and superuser (default: 'postgres')
  -g <gid>      group for data files (default: primary group of owner)
  -d <dir>      data directory (default: 
                /var/lib/postgresql/<version>/<cluster name>)
  -s <dir>      socket directory (default: /var/run/postgresql for clusters
                owned by 'postgres', /tmp for other clusters)
  -l <dir>      path to desired log file (default:
                /var/log/postgresql/postgresql-<version>-<cluster>.log)
  --locale <encoding>
                set cluster locale (default: inherit from environment)
  --lc-collate/ctype/messages/monetary/numeric/time <locale>
                like --locale, but only set for a particular category
  -e <encoding> Default encoding (default: derived from locale)
  -p <port>     port number (default: next free port starting from 5432)
  --start       start the cluster after creating it
  --start-conf auto|manual|disabled
                Set automatic startup behaviour in start.conf (default: 'auto')
  --createclusterconf=file alternative createcluster.conf to use
  --environment=file alternative environment file to use
  <initdb options> other options to pass to initdb
```

**Comment by dev-zero** [comment]
just remember: `pg_ctlcluster` and `pg_createcluster` are Debian-specific.

**Comment by ltalirz** [comment]
I played a bit around with this. It turns out that the debian tools like `pg_createcluster` [always require root privileges](https://stackoverflow.com/a/40645116/1069467), since they write their configuration files to `/etc` and this cannot be changed.

`pg_ctl` is still available on ubuntu 18.04 (e.g. `/usr/lib/postgresql/10/bin/pg_ctl`), it is just not in the `PATH` by default.

This leaves essentially two options if `pg_ctl` is not found in the `PATH`:
 1. We fall back to `pg_createcluster`, if found, and need to deal with `sudo` 
 2. We try to find `pg_ctl` using something like `locate` on debian systems.

I will give 2. a try.

**Comment by dev-zero** [comment]
How about something like:

1. first try to find `pg_ctl` in $PATH
2. if not found, then glob `/usr/lib/postgresql/*/bin/pg_ctl`, parse the version-number as `float`, compare & select highest

this would avoid the need for an up-to-date `locate` database and the `locate` command.

**Comment by dev-zero** [comment]
Inspired by Debian's `PgCommon.pm` (the postgresql-common package which contains `pg_createcluster`):

```perl
[...]

# Return an array of all available PostgreSQL versions
sub get_versions {
    my @versions = ();
    if (opendir (D, $binroot)) {
    my $entry;
        while (defined ($entry = readdir D)) {
            next if $entry eq '.' || $entry eq '..';
        ($entry) = $entry =~ /^(\d+\.\d+)$/; # untaint
            push @versions, $entry if get_program_path ('psql', $entry);
        }
        closedir D;
    }
    return @versions;
}

# Return the newest available version
sub get_newest_version {
    my $newest = 0;
    map { $newest = $_ if $newest < $_ } get_versions;
    return $newest;
}
[...]
```

Maybe something like the following would be sufficient (with minimal error handling):

```python
import glob
import re

try:
    pg_ctls = {float(re.search(r'\d+\.\d+', p).group()): p for p in glob.glob('/usr/lib/postgresql/*/bin/pg_ctl')}
    pg_ctl = pg_ctls[max(pg_ctls)]

except (AttributeError, ValueError):  # AttributeError occurs if re.search returns None, ValueError if pg_ctls is empty
    raise NotFoundException("no pg_ctl found in /usr/lib/postgresql/*/bin")
```

**Comment by ltalirz** [comment]
@dev-zero Thanks for the nice suggestion - if you like, we can keep the issue open for this.

I feel a bit stupid, however, to realize that the fallback to `locate` [is already in the code and working](https://github.com/jamesnunn/pgtest/blob/master/pgtest/pgtest.py#L86).
Indeed, the only reason the tests are failing on Ubuntu 18.04 is #9. I'll make a PR.

**Comment by ltalirz** [comment]
@dev-zero added your suggestion with a slightly modified regex (`10` is also a valid postgres version) in #11.
